extends Node

var songs = [
	"gumi-coma",
	"hatsune-miku-disappearance-of-hatsune-miku",
	"hatsune-miku-ghost-city",
	"hatsune-miku-god-ish",
	"hatsune-miku-hated-by-life-itself",
	"hatsune-miku-jigsaw-puzzle",
	"hatsune-miku-karakuri-pierro",
	"hatsune-miku-knife",
	"hatsune-miku-romeo-and-cinderella",
	"hatsune-miku-senbonzakura",
	"hatsune-miku-spica",
	"hatsune-miku-world-is-mine",
	"mimi-sayonara-wa-iwanaidesa",
	"rokudenashi-ambiguous",
	"rokudenashi-flame-of-love",
	"rokudenashi-one-voice",
	"tsukuyomi-ikiru-yosuga",
	"yoasobi-yoru-ni-kakeru",
	"yurri-canon-ft-gumi-dareka-no-shinzou-ni-naretara",
	"yurri-canon-ft-gumi-kardia",
]

var songs_title = [
	"gumi: coma",
	"hatsune miku: disappearance of hatsune-miku",
	"hatsune miku: ghost city",
	"hatsune miku: god ish",
	"hatsune miku: hated by life itself",
	"hatsune miku: jigsaw puzzle",
	"hatsune miku: karakuri pierro",
	"hatsune miku: knife",
	"hatsune miku: romeo and cinderella",
	"hatsune miku: senbonzakura",
	"hatsune miku: spica",
	"hatsune miku: world is mine",
	"mimi: sayonara wa iwanaidesa",
	"rokudenashi: ambiguous",
	"rokudenashi: flame of love",
	"rokudenashi: one voice",
	"tsukuyomi: ikiru yosuga",
	"yoasobi: yoru ni kakeru",
	"yurri canon ft gumi: dareka no shinzou ni naretara",
	"yurri canon ft gumi: kardia",
]
